-- Add column for video URL
ALTER TABLE dsa_topics ADD COLUMN IF NOT EXISTS video_url VARCHAR(255);

UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=OMcxQ3IY-qc' WHERE title = 'Introduction to Programming';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=AxB78suyqr8' WHERE title = 'Loops & Conditionals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=cMTFGOmYT9E' WHERE title = 'Functions in C++';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=R5BEcvTVZj0' WHERE title = 'STL Containers';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=o-WpVoRgSj4' WHERE title = 'STL Algorithms';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=4EDbe3lhHOM' WHERE title = 'Iterators in C++';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=efET3lxYCkM' WHERE title = 'Fast Input/Output Techniques';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=abZEVCRYZP8' WHERE title = 'Big O Notation Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=bvskLsirgrk' WHERE title = 'Space Complexity';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=EEEa0u0ZQio' WHERE title = 'Introduction to Arrays';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=EEEa0u0ZQio' WHERE title = 'Vectors - Dynamic Arrays';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=nZe7P674xZo' WHERE title = 'Prefix Sum & Difference Array';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=EEEa0u0ZQio' WHERE title = '2D Arrays & Matrix Operations';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=v_qm2Sce7as' WHERE title = 'Two Pointers Technique';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Zlx7gmt3lBU' WHERE title = 'Sliding Window Technique';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=sYs0L1vxRjo' WHERE title = 'Kadane''s Algorithm';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=abZEVCRYZP8' WHERE title = 'Introduction to Strings';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=abZEVCRYZP8' WHERE title = 'String Manipulation Techniques';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=uy_C8BkuN9w' WHERE title = 'Anagram and Substring Problems';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=nZe7P674xZo' WHERE title = 'Trie (Prefix Tree)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=egRrgj8JOdY' WHERE title = 'Binary Search Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=sYs0L1vxRjo' WHERE title = 'Sorting Algorithms';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=gcYvFVZ_LUA' WHERE title = 'Binary Search Advanced (Lower/Upper Bound, Rotated Array)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=d59iXqly5FY' WHERE title = 'Understanding Recursion';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=4KpSXSIPH2s' WHERE title = 'Backtracking Framework';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=u0e29JIdxZU' WHERE title = 'Subset Generation & Combination Sum';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=ZT2o8iDCk6o' WHERE title = 'Reversing a Linked List';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=JK1oBTQRWRA' WHERE title = 'Stack Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=JK1oBTQRWRA' WHERE title = 'Queue Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=JK1oBTQRWRA' WHERE title = 'Monotonic Stack Pattern';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=T-E3hWEPWWU' WHERE title = 'Next Greater Element Problems';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=hE97YT-347U' WHERE title = 'Tree Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=egRrgj8JOdY' WHERE title = 'Binary Search Trees';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=il2HXsJPGO4' WHERE title = 'Lowest Common Ancestor (LCA)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=cWvruDR-hJA' WHERE title = 'Merge K Sorted Lists/Arrays';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=hE97YT-347U' WHERE title = 'Graph Representation';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=9_ftWKch6vI' WHERE title = 'BFS and DFS';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=sYs0L1vxRjo' WHERE title = 'Dijkstra''s Algorithm';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=cWvruDR-hJA' WHERE title = 'Topological Sort';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=zEAmQqOpfzM' WHERE title = 'Disjoint Set Union (DSU/Union-Find)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=utZcJ0leZ_g' WHERE title = 'BFS Applications & Variations';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=zBbRgLpeZus' WHERE title = 'DFS Applications (Cycle, Components, Paths)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=hE97YT-347U' WHERE title = 'Bipartite Graph Detection';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=zBbRgLpeZus' WHERE title = 'Strongly Connected Components (Kosaraju)';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=uy_C8BkuN9w' WHERE title = 'Classic DP Problems';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=4a_zLjG4kXU' WHERE title = '0/1 Knapsack & Variations';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=vz0P_2V0y7M' WHERE title = 'Matrix Chain Multiplication';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=XjtYsFjXtoE' WHERE title = 'Bit Manipulation Fundamentals';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=mqCdA8mcJeo' WHERE title = 'Bit Masking Techniques';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=utZcJ0leZ_g' WHERE title = 'GCD & LCM';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=T8PaMnb0GPo' WHERE title = 'Prime Numbers & Sieve';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=RCq5TYMZEwg' WHERE title = 'Modular Arithmetic';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=J63JPxqmyzg' WHERE title = 'Fast Exponentiation & Binary Exponentiation';
UPDATE dsa_topics SET video_url = 'https://www.youtube.com/watch?v=Ljo4tWiuZL0' WHERE title = '📝 Extra Practice';
